apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-prodcution-ec2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: complete-prodcution-ec2-app
  template:
    metadata:
      labels:
        app: complete-prodcution-ec2-app
    spec:
      containers:
        - name: complete-prodcution-ec2-app
          image: deepashreekl/complete-prodcution-ec2-pipeline:1.0.0-11
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
