apiVersion: v1
kind: Service
metadata:
  name: complete-prodcution-ec2-svc
  labels:
  app: complete-prodcution-ec2-app
spec:
  selector:
    app: complete-prodcution-ec2-app
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer    
